version: "3.8"

services:
#  app:
#    build:
#      context: .
#      dockerfile: ./docker/Dockerfile
#    env_file:
#      - .env
#    ports:
#      - "8001:8001"

  app-dev:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8001:8001"
    env_file:
      - .env
    command: ["air"]